HewlettPackard/lustre_exporter

sources/procfs.go
=> sources/procfs: Add the first metric

sources/procfs.go
=> Add MDS metrics

.promu.yml, README.md, lustre_exporter.go
=> Update repo-dependent names to HewlettPackard

Makefile
=> Add 'make clean' support to Makefile

sources/procfs.go
=> Reset metricType to single

README.md
As some other HPE github projects have done, explicitly stating the CLA requirements of our (possibly robot) overlords. 
=> Add Contributing details to README

lustre_exporter.go, sources/procfs.go
=> Clean up spelling mistakes

sources/procfs.go
=> Use 'gofmt -s' to simplify code

sources/procfs.go
Replace all nested maps in the metric definitions with structs for direct access of metric elements.
=> Refactor stats to use structs

README.md
Added:
* Link to prometheus.io
* Go Report Card
Changed:
* Design plans item #1 updated to reflect our belief that we're fairly complete.
=> Update README (various items)

sources/procfs.go
Now able to use custom Prometheus names for all metrics. Simply change the `promName` field in the metric initialization with the desired name.
Fixes #24
=> Allow custom names

sources/procfs.go
Add every metric located in the 'job_stats' file including all job_stats from the MDTs.
=> Add all jobstats metrics

sources/procfs.go
=> Fix syntax error in initialization

sources/procfs.go
=> Include metrics from md_stats

sources/procfs.go
=> Update brw_size help text

sources/procfs.go
As written in the help text, nodes marked as 'healthy' will have a value
of 1 while nodes of any other status will be marked 0. Due to Prometheus
requiring a numeric value for all results, there isn't a readily available
way to parse unhealthy targets (such as an OST), hence the widespread
labelling of unhealthy.
Fixes #53 
=> Add 'health_check' metric

sources/procfs.go
Use of the variadic parameter allows us to specify an unknown number of labels
to the MustNewConstMetric function, which enables us to consolidate
CounterValue functions into a single unit. This will allow us to use only the
desired type without creating new functions for various types for metrics with
unique labels.
=> Consolidate CounterValue functions

.promu.yml
=> Properly parse BuildUser

sources/procfs.go
The calling metric function can now be set to easily specify which
metric type should be used for Prometheus.
=> Specify Prometheus metric type for all metrics

.travis.yml, README.md
=> Add Travis-CI

lustre_exporter.go, sources/proc_common.go, sources/proc_common_test.go, sources/procfs.go, sources/procfs_test.go, sources/procsys.go, sources/procsys_test.go, sources/stats_integration_test.go
=> Add LNET statistics

sources/procfs.go
=> Don't populate empty labels for rpc_stats

sources/procfs.go
=> Fix RPC metric names and types

sources/procfs.go
=> Add wildcard to client metrics

sources/procfs.go
=> Update write_minimum_size_bytes help text

lustre_exporter_test.go, proc/fs/lustre/sptlrpc/encrypt_page_pools, sources/procfs.go
=> Add Kerberos stats

lustre_exporter.go
=> Log to stdout what sub-components are enabled

lustre_exporter_test.go
=> Clean up simple lint error

systemd/lustre_exporter, systemd/lustre_exporter.service
These two files are used as the source for RPM/DEB packaging.
=> Add systemd directory for service files

CHANGELOG.md
=> Update changelog for 1.1.0 release

CHANGELOG.md
=> Update CHANGELOG for v2.0.0

.travis.yml, Makefile, sources/proc_common.go, sources/procsys.go
=> Update linter to golangci-lint and fix associated issues
