sources/procfs.go

If a metric doesn't exist, it should be skipped instead of returned. This is especially pertinant when running on certain storage nodes. For example, if running on the MGS node and the OSS metrics are not disabled, the collector would not export MGS metrics as it would return after the first OSS metric is not found.

Skip metrics that don't exist

---

sources/procfs.go

Refactor collector to easily include help text for each metric.

Add help text

---

sources/procfs.go

Adds metrics from the obdfilter directory on OSS servers. Includes help text for all metrics.

Add metrics from the obdfilter

---

sources/procfs.go

Add MGS metrics

---

sources/procfs.go

The Block Read/Write (BRW) stats file includes the following (paraphrased from [the Lustre manual](http://wiki.old.lustre.org/manual/LustreManual20_HTML/LustreProc.html#50438271_55057))
- Pages per block R/W: Counter value of the number of pages per RPC (remote procedure call)
- Discontiguous pages: Counter value of the number of logical discontinuities per RPC
- I/O Time: The time in milliseconds the filesystem has spent processing various object sizes
- Disk I/O Size: Counter value of the number of operations the filesystem has performed for the given size
- Disk I/O's in Flight: Current number of I/O operations that are processing during the snapshot

Parse BRW Stats

---

sources/procfs.go

The 'stats' map was inefficient and confuscated in its original form. This refactor flattens the map for easier unravelling, while also improving the performance of the collector by removing the nested loops in 'parseFile'. Additionally, this change allows for future potential scalability if the 'stats' map ever needs to be expanded. The logical structure of the map can now stay unchanged without impacting other code snippets.

Flatten 'stats' map and simplify 'stats' logic

---

sources/procfs.go

Originally, all metric names began with 'lustre_lustre_'. According to the documentation on BuildFQName, "BuildFQName joins the given three name components by '_'. Empty name components are ignored." Since all of the metrics in the lustre_exporter are in the 'lustre' namespace and a single subsystem, there is no reason to specify a subsystem. Fixes #11.

Remove redundant metric prefixes

---

sources/procfs.go

In certain cases where the read_bytes metric is not found in the 'stats' file, the exporter would fail when trying to write to a nil map. This patch fixes the issue.

Fix nil map error

---

sources/procfs.go

Add distributed lock manager singlestat files

---

sources/procfs.go

Now able to read the following on a per-job basis for both read and write:
* samples: Total number of samples that have been collected for the given metric
* min: Minimum byte size that has been read/written
* max: Maximum byte size that has been read/written
* total: Total number of bytes that have been read/written for the duration of the job

Collect Job Stats

---

sources/procfs.go

We were calling them OSS nodes, which the metrics clearly are not. Renamed the whole field set as OST to avoid any confusion. Fixes issue #25.

Fix incorrect naming convention for OSTs

---

sources/procfs.go

Specifically, adding support for the num_exports metric for now.

Add support for MDT metrics

---

lustre_exporter.go
sources/procfs.go
sources/source.go

Clean up golint warnings

---

sources/procfs.go

Now able to directly access metric elements and easily specify a unique Prometheus name at initialization.
Note that I have not yet updated the names to be Prometheus compliant.

Refactor metric initialization to use structs

---

sources/procfs.go

Lowercase all metric labels

---

sources/procfs.go

In case a particular jobstats metric isn't located on a node, skip over
it instead of trying to parse a value, yielding unexpected results.

Skip jobstats metric if they don't exist

---

lustre_exporter.go

Hi @joehandzik, I am fixing this bug reported by go vet, and related to the changes in #61.
```
$ make 
>> formatting code
>> vetting code
lustre_exporter.go:60: range variable c captured by func literal
exit status 1
Makefile:34: recipe for target 'vet' failed
make: *** [vet] Error 1
``` 
As explanation I can refer you [this](https://github.com/gnhuy91/til/issues/7). Thanks @knweiss!

Fix range variable c captured by func literal

---

.gitignore
.travis.yml
Makefile
README.md

I made some small aesthetic changes to the [Makefile](Makefile) and fix also a `vet` warning,
```
>> formatting code
>> vetting code
lustre_exporter.go:60: range variable c captured by func literal
exit status 1
Makefile:35: recipe for target 'vet' failed
make: *** [vet] Error 1
```
In addition I create a (.gitignore)(gitignore) file to exclude ***~** and the binary created **lustre_exporter**.
I hope you agree with the changes. Thanks!

Makefile improvements

---

sources/procfs.go

In some situations, a metric that is being queried by the lustre_exporter
might not be tracked in the job_stats file and can cause GO to panic.
This update skips over any metrics that don't provide valid responses.

Skip empty jobstats

---

sources/brw_stats_integration_test.go
sources/jobstats_integration_test.go
sources/procfs_test.go
sources/stats_integration_test.go

This is a first pass at adding unit/integration tests. Let me know if I can expand or improve them.

Add unit tests

---

sources/procfs.go

Add client statistics

---

sources/procfs.go

Expand metrics collected by stats files

---

lustre_exporter.go

Using a string slice allows new sources to be added easily without
worry of breaking the desired format. For example, if a space is
located in the enabledSources declaration, lustre_exporter will
throw a fatal error that the intended source cannot be found.

Allow multiple sources

---

sources/procfs.go
sources/procfs_test.go

Previously, the regex matcher intended to match floats, but would
instead match any character between two numbers as opposed to a
period. For example, the numbers '1965 1966' would be parsed as a
single string ('1965 1966') instead of two strings ('1965' '1966').
This update now properly parses both floats and integers.

Update float parsing patterns

---

sources/procfs.go
sources/procfs_test.go
sources/source.go

Cleanup errors caught by megacheck

---

.travis.yml
Makefile

Hi,
I just found [megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck) as a part of the [go-tools](https://github.com/dominikh/go-tools) project and wanted to give it a try. 
As you can see above, this seems to be worth. 
```
$ make
>> formatting code
>> vetting code
>> megacheck code
sources/procfs.go:84:2: field subsystem is unused (U1000)
sources/procfs.go:534:3: should replace loop with metricList = append(metricList, statsList...) (S1011)
sources/procfs.go:623:3: should replace loop with metricList = append(metricList, jobList...) (S1011)
sources/procfs.go:714:22: this value of err is never used (SA4006)
sources/procfs_test.go:207:2: this value of metricList is never used (SA4006)
sources/source.go:31:6: type typedDesc is unused (U1000)
Makefile:39: recipe for …
```

Add Megacheck

---

sources/proc_common.go
sources/proc_common_test.go
sources/procfs.go

This will work through IO sizes of Gigabytes
Fixes #50

Convert brw_stats sizes to bytes

---

sources/procfs.go
sources/stats_integration_test.go

Conform to the way getJobStats*Metrics work.
Fixes issue #89

Reorder getStats*Metrics arguments

---

sources/procfs.go

Add RPC stats for the client

---

lustre_exporter.go
sources/procfs.go
sources/procsys.go
sources/source.go

This is not to say that it's not possible at all for something to go wrong and require that we re-add them at some point, but as the code is currently written, these error return values would never actually be something other than nil.

Remove support for errors that won't happen

---

.travis.yml
Makefile
lustre_exporter.go
sources/proc_common_test.go
sources/procfs.go
sources/procfs_test.go
sources/procsys.go
vendor/github.com/Sirupsen/logrus/README.md
vendor/github.com/Sirupsen/logrus/doc.go
vendor/github.com/Sirupsen/logrus/entry.go
vendor/github.com/Sirupsen/logrus/exported.go
vendor/github.com/Sirupsen/logrus/json_formatter.go
vendor/github.com/Sirupsen/logrus/logger.go
vendor/github.com/Sirupsen/logrus/logrus.go
vendor/github.com/Sirupsen/logrus/terminal_windows.go
vendor/github.com/golang/protobuf/proto/lib.go
vendor/github.com/prometheus/client_golang/prometheus/doc.go
vendor/github.com/prometheus/client_golang/prometheus/http.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_7.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/common/log/log.go
vendor/github.com/prometheus/procfs/ipvs.go
vendor/github.com/prometheus/procfs/mountstats.go
vendor/github.com/prometheus/procfs/xfrm.go
vendor/vendor.json

Hi @joehandzik @roclark,
I am creating this PR adding [gometalinter](https://github.com/alecthomas/gometalinter) support. There is a bunch of different Linters that you can list with `gometalinter -h`, and you can disable some that are maybe not relevant to you.
Travis is failing of course, but you can just analyze what you want to fix and what you would simply want to disable.
I personally think this tool is much more powerful, and offer editor integration too!

Add `gometalinter` support

---

sources/proc_common.go
sources/procfs.go
sources/procsys.go

The global initialization of the number regex parser reduces the total
number of mallocs by a factor of approximately 10.

Move all number parsing to separate function

---

lustre_exporter_test.go
sources/procfs.go

The 'max wait time' metric is a fractional value which cannot be parsed
as a float and in-turn can't be used with Prometheus. Instead,
re-capture the 'out of mem' metric.

Replace 'max wait time' with 'out of mem'

---

sources/proc_common.go
sources/procfs.go
sources/procfs_test.go
sources/procsys.go

For any possible metric value, always assume the value could require being parsed as a floating point value. This has the positive side-effect of eliminating some conversions to float64 across the codebase.
Fixes issue #111.

Use float64 instead of uint64 for all Prom metrics

---

README.md
lustre_exporter.go
lustre_exporter_test.go
sources/proc_common.go
sources/procfs.go
sources/procsys.go

Change flags from binary to string arguments, and introduce the concept of disabled, core, and extended.
Fixes issue #116.

Change flag behavior to introduce metric priority levels

---

README.md

Two dashes are required for the new kingpin flags (single dash implies an abbreviation of some kind). Clarify that in the README.

Add double-dash to example flags

---

CHANGELOG.md

Update changelog to prepare for version 1.0.0 tag

---

sources/proc_common.go
sources/procfs.go
sources/procfs_test.go
sources/procsys.go
sources/sysfs.go

When enable `jobid_var = procname_uid` in lustre, the lustre client also collect job id like `<process_name>.<uid>` .
The current lustre_exporter implement has missing to handle process name in job id, which also cause the issue #135

Fix job id missing process name
